org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11

mod_id=declinabledeathmessages
mod_name=Declinable Death Messages
mod_version=2.0.0

maven_group=me.declinabledeathmessages
mod_group_id=me.declinabledeathmessages
mod_license=CC0-1.0

# Fabric
loader_version=0.19.3
fabric_api_version=0.141.6+1.21.11
loom_version=1.17-SNAPSHOT

# NeoForge
neo_version=21.11.45
minecraft_version_range=[1.21.11]

# Dependencies
cloth_config_version=21.11.153