org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

org.gradle.java.home=D:/Program Files/Java/jdk-25

minecraft_version=26.1.2

mod_id=declinabledeathmessages
mod_name=Declinable Death Messages
mod_version=2.0.0

maven_group=me.declinabledeathmessages
mod_group_id=me.declinabledeathmessages

# Fabric
loader_version=0.19.3
fabric_api_version=0.155.0+26.1.2
loom_version=1.17.16

# NeoForge
neo_version=26.1.2.87
minecraft_version_range=[26.1.2]
mod_license=CC0-1.0

# Dependencies
cloth_config_version=26.1.154